// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package queries

import (
	"context"
)

const checkPendingRequestExists = `-- name: CheckPendingRequestExists :one
select exists (
  select 1
  from request
  where player_id = ?
  and kind = ?
  and pending = true)
`

type CheckPendingRequestExistsParams struct {
	PlayerID string
	Kind     string
}

func (q *Queries) CheckPendingRequestExists(ctx context.Context, arg CheckPendingRequestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPendingRequestExists, arg.PlayerID, arg.Kind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertRequest = `-- name: InsertRequest :one
insert into request (player_id, kind, content)
  values (?, ?, ?)
  returning id, player_id, kind, content, pending, created_at
`

type InsertRequestParams struct {
	PlayerID string
	Kind     string
	Content  string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, insertRequest, arg.PlayerID, arg.Kind, arg.Content)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Content,
		&i.Pending,
		&i.CreatedAt,
	)
	return i, err
}

const resolveRequest = `-- name: ResolveRequest :exec
update request
  set pending = false
  where id = ?
`

func (q *Queries) ResolveRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resolveRequest, id)
	return err
}

const selectPendingRequests = `-- name: SelectPendingRequests :many
select player.id, player.role, player.alias, player.soldier_div, player.demo_div, player.avatar_url, player.trade_token, player.tempus_id, player.country, player.country_code, player.class_pref, player.map_pref, player.launcher_pref, player.created_at, request.id, request.player_id, request.kind, request.content, request.pending, request.created_at from request
  join player on player.id = request.player_id
  where pending = true
`

type SelectPendingRequestsRow struct {
	Player  Player
	Request Request
}

func (q *Queries) SelectPendingRequests(ctx context.Context) ([]SelectPendingRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPendingRequestsRow
	for rows.Next() {
		var i SelectPendingRequestsRow
		if err := rows.Scan(
			&i.Player.ID,
			&i.Player.Role,
			&i.Player.Alias,
			&i.Player.SoldierDiv,
			&i.Player.DemoDiv,
			&i.Player.AvatarUrl,
			&i.Player.TradeToken,
			&i.Player.TempusID,
			&i.Player.Country,
			&i.Player.CountryCode,
			&i.Player.ClassPref,
			&i.Player.MapPref,
			&i.Player.LauncherPref,
			&i.Player.CreatedAt,
			&i.Request.ID,
			&i.Request.PlayerID,
			&i.Request.Kind,
			&i.Request.Content,
			&i.Request.Pending,
			&i.Request.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPlayerRequests = `-- name: SelectPlayerRequests :many
select player.id, player.role, player.alias, player.soldier_div, player.demo_div, player.avatar_url, player.trade_token, player.tempus_id, player.country, player.country_code, player.class_pref, player.map_pref, player.launcher_pref, player.created_at, request.id, request.player_id, request.kind, request.content, request.pending, request.created_at from request
  join player on player.id = request.player_id
  where player_id = ?
  and pending = true
`

type SelectPlayerRequestsRow struct {
	Player  Player
	Request Request
}

func (q *Queries) SelectPlayerRequests(ctx context.Context, playerID string) ([]SelectPlayerRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectPlayerRequests, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPlayerRequestsRow
	for rows.Next() {
		var i SelectPlayerRequestsRow
		if err := rows.Scan(
			&i.Player.ID,
			&i.Player.Role,
			&i.Player.Alias,
			&i.Player.SoldierDiv,
			&i.Player.DemoDiv,
			&i.Player.AvatarUrl,
			&i.Player.TradeToken,
			&i.Player.TempusID,
			&i.Player.Country,
			&i.Player.CountryCode,
			&i.Player.ClassPref,
			&i.Player.MapPref,
			&i.Player.LauncherPref,
			&i.Player.CreatedAt,
			&i.Request.ID,
			&i.Request.PlayerID,
			&i.Request.Kind,
			&i.Request.Content,
			&i.Request.Pending,
			&i.Request.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
