// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package queries

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
select count(*) from event
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayers = `-- name: CountPlayers :one
select count(*) from player
`

func (q *Queries) CountPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTimes = `-- name: CountTimes :one
select count(*) from time
`

func (q *Queries) CountTimes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTimes)
	var count int64
	err := row.Scan(&count)
	return count, err
}
